spring:
  application:
    name: hobby
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hobby
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.yogosaza.hobby.domain, com.yogosaza.hobby.dto
  mapper-locations: classpath:mapper/*.xml
